### ISSUE TITLE
Any plans to update to 1.20.1?

### ISSUE THREAD

**Issue by Nephalem0** [Sreeraj-S/PokemonToItem#1]
As the title says, I think your mod is super useful, any plans to update it?

**Comment by Sreeraj-S** [comment]
Sure... I havnt touched it since I had a lot of college works to complete... Will try to update it within next 48 hr. Sorry for the delay. 😊

**Comment by Nephalem0** [comment]
Tyvm! Hyped to see the update then

**Comment by Nephalem0** [comment]
I don't mean to rush but will the update come soon?

**Comment by Sreeraj-S** [comment]
Sorry for the delay...  I've just updated the PokemonToItem mod to support Minecraft version 1.20.1!  You can grab the latest version and dive into the fun by visiting the [PokemonToItem Modrinth page](https://modrinth.com/mod/pokemontoitem). 😊
Thanks for the reminder. I'm currently swamped with college work, so I might not catch up on Minecraft updates for a while. If there's a new update, feel free to open an issue, and I'd be more than happy to jump in, update the mod, and release it.
