### ISSUE TITLE
Permissions don't won't

### ISSUE THREAD

**Issue by Nephalem0** [Sreeraj-S/PokemonToItem#2]
Hi! I am trying to add perms to the commands but it doesn't seem to work
![noperm](https://github.com/Sreeraj-S/PokemonToItem/assets/73258462/5a49063c-c60c-4a4c-a7d6-036105b77bc3)
![perms](https://github.com/Sreeraj-S/PokemonToItem/assets/73258462/b9dd126f-0cff-4e2d-bd84-287262abbec7)

**Comment by Sreeraj-S** [comment]
Can you send an ScreenShot of your Config file?

**Comment by Sreeraj-S** [comment]
Thanks for pointing out the permissions. 🙌 I'll make sure to update the readme with the correct permission (`cobblemon.pokemontoitem.command.poketoitem`). Also, I've noticed the similarity in permissions for `itemtopoke` and `poketoitem` commands—I'll fix that too in the upcoming release.  If you have any more insights or questions, feel free to share.

**Comment by Nephalem0** [comment]
Thank you! I have found a temporary fix by doing minecraft.poketoitem.poketoirm and minecraft.poketoitem.itemtopoke

**Comment by Sreeraj-S** [comment]
Oh great!!! I have released a new version of the mod since I found that poketoitem and itemtopoke used the same permission. You can download it from [here](https://modrinth.com/mod/pokemontoitem/versions#all-versions)
