### ISSUE TITLE
Pokemon deleted when with a full inventory

### ISSUE THREAD

**Issue by Nephalem0** [Sreeraj-S/PokemonToItem#3]
HI!

It seems that if someone does /poketoitem with a full inventory the pokemon is deleted, is it possible to add that if you have a full inventory the pokemon is dropped on the floor instead?
Thank you!

**Comment by Sreeraj-S** [comment]
Oh, Will look into it!!! There will be a delay since I have my semester exams going on.

**Comment by Sreeraj-S** [comment]
I've fixed the bug and released the fix on GitHub. I'll now proceed to update it on Modrinth.😊 If you want, you can download from [releases](https://github.com/Sreeraj-S/PokemonToItem/releases/tag/0.1.1%2B1.20.1)

**Comment by Nephalem0** [comment]
Thank you so much!
