### ISSUE TITLE
Pokemon menu

### ISSUE THREAD

**Issue by Nephalem0** [Sreeraj-S/PokemonToItem#4]
Hi! Sorry for reaching out like this but idk rly where else. I was wondering if it would be possible to make a separate mod that pulls out the poketoitem menu? It would be great for making custom applications if after you click on the mod you can customize the response per menu. Or allowing even to have tired commands to how you bring up the menu to make several. Like for a tm or for a poke editor! I would gladly even pay for a mod like that

**Comment by Sreeraj-S** [comment]
I didn't understand the idea. So is it like you want a poketoitem menu to open by pressing a button instead of the command? if you want contact me through discord, join the [server](https://discord.gg/ah9QRAmm). P.S Don't expect much in the server just created only😋
