### ISSUE TITLE
(Feature Request)

### ISSUE THREAD

**Issue by rdaniels0906** [Sreeraj-S/PokemonToItem#5]
This does not work in multi-server setups where inventory sync allows players to transfer the items to another server due the mod not being able to find the .nbt file in the config folder. (Because its on the original server.)

Is there any reason why all the needed information can't be stored in the nbt data of the item itself?

**Comment by Sreeraj-S** [comment]
Hello!

Thank you for bringing this issue to my attention. I apologize for the delayed response; I had semester exams, which kept me a bit busy.

I'm pleased to inform you that I have updated the mod to address the problem you've mentioned. The latest version now stores all necessary information in the NBT data of the item itself, which should resolve the issue with inventory sync in multi-server setups.

You can download the latest version of the mod from Modrinth:
- [Fabric version 0.1.2](https://modrinth.com/mod/pokemontoitem/version/0.1.2+1.20.1)
- [Forge version 0.1.2](https://modrinth.com/mod/pokemontoitem/version/xthYajWk)

Please test it out and let me know if you encounter any further issues. Your feedback is invaluable, and I'm here to help with any other concerns or questions you might have.

Thank you for your patience and support!
